### ISSUE TITLE
Find all files with matching paths

### ISSUE THREAD

**Issue by martinResearch** [r1chardj0n3s/parse#135]
Thank you for this very useful library. 
I would like very much to have a function in the parse module to find all files in a folder and its subfolders whose relative path to the root folder matches a specified fstring format pattern. 
Similarly to the glob.glob function it would walk through the file system to find matching files but would use parse instead of fnmatch. It would preferably avoid listing all files in the root folder subfolders, similarly to glob. It would be a great alternative to glob. Would it make sense to add this functionality to the parse module, or is out of its scope?

**Comment by mathause** [comment]
Take a look at https://github.com/mathause/filefinder - however, I am not sure it matches your specs & under the hood it also uses `glob` but it also parses the patterns such that you get the metadata back.

It could however be possible to write a custom function to walk the filesystem and use parse to find the paths matching the pattern.

**Comment by wimglenn** [comment]
Yeah, this is out of scope.  `parse` currently is totally agnostic about any filesystem, it just works with strings.

For a glob replacement which uses parse instead of wildmatch, recommend to just put together some for-loop with [`os.walk`](https://docs.python.org/3/library/os.html#os.walk) + `parse`.
