### ISSUE TITLE
Document behaviour when the template is ambiguous

### ISSUE THREAD

**Issue by wimglenn** [r1chardj0n3s/parse#52]
Example:

```
>>> pattern = '{dir1}/{dir2}'
>>> data = 'root/parent/subdir'
>>> parse(pattern, data).named
{'dir1': 'root', 'dir2': 'parent/subdir'}
```

But `{'dir1': 'root/parent', 'dir2': 'subdir'}` is also fitting the pattern.  Is this behaviour is reliable, or should it be considered implementation detail?  I couldn't find it in the docs anywhere.  

Is there anyway to coerce the result one way or the other?

**Comment by r1chardj0n3s** [comment]
Indeed the source text and pattern in question do result in ambiguity. The behaviour is reliable - the minimum matched if possible. I'll think about how that might be written into the docs.

The specific case in question though is a good example of using a more domain-specific parser that understands paths (i.e. pathlib) rather than a generic parser.
